/**
 * Small deterministic PRNG (linear congruential generator - same recurrence used by
 * test/cube-checks.ts's `seeded()` helper) so maze/scramble generation can be reproduced exactly
 * from a numeric seed. Without this, a number cited in a written report ("A* expanded 47 nodes on
 * this instance") can never be regenerated by anyone re-running the app - the seed makes "this
 * instance" a citable, reproducible thing instead of whatever Math.random() happened to draw.
 */
export function seededRng(seed: number): () => number {
  let s = (seed >>> 0) || 1;
  return () => {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    return s / 0x7fffffff;
  };
}

export function randomSeed(): number {
  return Math.floor(Math.random() * 0x7fffffff);
}
